### ISSUE TITLE
Execution

### ISSUE THREAD

**Issue by mhmbello** [MohaElbadry/Projet_Web_TP#1]
Salut
je n'arrive pas a lancer le site

**Comment by MohaElbadry** [comment]
Just follow the instruction and it will work correctly

**Comment by mhmbello** [comment]
Alright sir

________________________________
De : mohammed el badry ***@***.***>
Envoyé : mercredi 21 février 2024 11:18
À : MohaElbadry/Projet_Web_TP ***@***.***>
Cc : mhmbello ***@***.***>; Author ***@***.***>
Objet : Re: [MohaElbadry/Projet_Web_TP] Execution (Issue #1)


Just follow the instruction and it will work correctly
